version: '3'
services:
  mindmap-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vue-mindmap
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run serve 